config/routes.rb
RoR::Application.routes.draw do
 resources :users
  resources :sessions, only: [:new, :create, :destroy]  
  resources :entries, only: [:create, :destroy]
  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete
  match '/delete', to: 'entries#destroy', via: :delete
  match '/blog', to: 'static_pages#blog'
  get "static_pages/blog"
  get "static_pages/home"
  get "static_pages/account"
  get "static_pages/help"
  root :to => 'static_pages#home'

end

app/models/entry.rb
class Entry < ActiveRecord::Base
  attr_accessible :content, :user_id
  validates(:user_id, presence: true)
  validates(:content, presence: true)  
  belongs_to :user
  default_scope order: 'entries.created_at DESC'
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  username               :string(255)
#  password               :string(255)
#  email                  :string(255)
#  fullname               :string(255)
#  password_confirmation :string(255)
#  password_token         :string(255)
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#

class User < ActiveRecord::Base
  attr_accessible :email, :fullname, :password, :password_confirmation, :remember_token, :username  
  validates(:username, presence: true)
  validates_uniqueness_of :username
  validates_uniqueness_of :email
  validates :username, :length => { :maximum => 10, :minimum=>6 }
  validates :password, :length => { :maximum => 10, :minimum=>6 }
  validates(:password_confirmation, presence: true)
  validates_confirmation_of :password
  validates(:fullname, presence: true) 
  validates(:email, presence: true)
  validates :email, :format => { :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i, :on => :create }
  before_save{ |user| user.username = username.downcase }
  before_save { |user| user.email = email.downcase }
  before_save:create_remember_token
  has_many :entries
#  before_save:encrypt_password # encrypt password before saving
  
  def self.check(username,password) 
	user =find_by_username(username)
	if user && user.password==password
		user
	else
		nil
	end
  end
  

  #include current_user's entries
  # removed , use show entries instead
#  def feed 
 # 	Entry.where("user_id= ?",id)
  #end
  def feed
  	Entry.where("user_id =?",id)
  end    
  private
  def create_remember_token
      if(self.remember_token==nil)
  	     self.remember_token = SecureRandom.urlsafe_base64
      end
  end
  

  def encrypt_password
#	salt = BCrypt::Engine.generate_salt
 # 	password = BCrypt::Engine.hash_secret(password, salt)
  end  

  
end

  

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  before_filter :signed_in_user, only: [:show, :create, :destroy]
  def create
  	@entry = current_user.entries.build(params[:entry])
    if @entry.save
      flash[:success] = "Posted successfully!"     
      
    else
      flash[:error] = "Please input content"	        
    end    
    redirect_to blog_path
  end   

  def destroy
    @entry = Entry.find(params[:id])
    @entry.destroy

    respond_to do |format|
      format.html { redirect_to blog_path }
      format.json { head :no_content }
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	
	#render signin form
	def new
		render 'new'
	end
	
	#Signin : create a new session
	def create
		user =User.check(params[:session][:username],params[:session][:password])		
		if user
			sign_in user
			redirect_to root_url, :notice => "Login successfully"
	  	else
            flash[:error] = 'Invalid username or password'
	  		render 'new'
	    end  		  
	end
	
	#Signout: call sign_out from sessionhelper
	def destroy
  		sign_out
  		flash[:error] = signed_in?
	  	new  	  	
	end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  	    
  end

  def account
  end

  def blog
  	@entry = current_user.entries.build if signed_in?
  	@entries = current_user.entries.paginate(page: params[:page],:per_page => 6) if signed_in?
  end

  def listofusers
  	@users = users.paginate(page: params[:page],:per_page => 6) if signed_in?
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])    
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to signin_path, notice: 'Sign up successfully' }
#        format.json { render json: @user, status: :created, location: @user }
#		redirect_to signin_path
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end
	

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	
	def sign_in(user)
		cookies[:remember_token] = { value:user.remember_token,expires: 20.years.from_now.utc }
		self.current_user=user
	end
	
	def current_user=(user)
    	@current_user = user
	end
	
	#find current user
	def current_user
    @current_user ||= User.find_by_remember_token(cookies[:remember_token])
  	end
  	
  	def sign_out
  		self.current_user=nil
  		cookies.delete(:remember_token)
  	end
  	
  	def signed_in?
    	!current_user.nil?
	end
	def signed_in_user
	    unless signed_in?
	      redirect_to signin_url, notice: "Please sign in."
    	end
    end
  
  
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
  #create avatar
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.username.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.username, class: "gravatar")
  end
end

app/views/entries/_entry.html.erb
<li>
  <span class="content"><%= entry.content %></span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(entry.created_at) %> ago.
  </span><%= link_to 'Delete', entry, method: :delete, data: { confirm: 'Are you sure?' } %>
</li>

app/views/entries/_new.html.erb
<%= form_for(@entry) do |f| %>
  <%= render 'shared/error', object: f.object %>
  <div class="field">
    <%= f.text_area :content, placeholder: "............." %>
  </div>
  <%= f.submit "Post", class: "btn btn-large btn-primary" %>  
<% end %>

app/views/entries/_show.html.erb
<% if @entries.any? %>
  <ol class="entries">
    <%= render partial: '/entries/entry', collection: @entries %>
  </ol>
  <%= will_paginate @entries %>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
	RUBY ON RAILS
  </small>  
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "sample app", '#', id: "logo" %>           	
		<div id='cssmenu'>
			<ul>
				<li ><%= link_to "Home", root_url %>	
				<li><%= link_to "Blog", "/static_pages/blog" %>						
				<li class='has-sub'><%= link_to "Account" %>	
					<% if signed_in? %>				
						<ul>
							<li><%= link_to "Edit profile ", edit_user_path(current_user) %></li>
							<li class='last'><%= link_to "Sign out", signout_path,:method=>:delete%></li>	
						</ul>
					<% else %>
						<ul>
							<li><%= link_to "Sign up ", signup_path %></li>
							<li class='last'><%= link_to "Sign in", signin_path %></li>	
						</ul>
					<% end %>
				</li>
			   <li><%= link_to "List of users", users_path %></li>  			  
			</ul>
		</div>     
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
	<title>Ruby on Rails Tutorial Sample App | <%= yield(:title) %></title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
  </head>
  <body>
  <%= render 'layouts/header' %>
    <div class="container">      
      <%= yield %>
      <%= render 'layouts/footer' %>    
    </div>
  </body>
</html>

app/views/shared/_entryform.html.erb
<%= form_for(@entry) do |f| %>
  <%= render 'shared/error', object: f.object %>
  <div class="field">
    <%= f.text_area :content, placeholder: "............." %>
  </div>
  <%= f.submit "Post", class: "btn btn-large btn-primary" %>
<% end %>

app/views/shared/_error.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<feed>
<% if @feed_items.any? %>
  <ol class="entries">
    <%= render partial: 'shared/feeditem', collection: @feed_items %>
  </ol>
  <%= will_paginate @feed_items %>
<% end %>
</feed>

app/views/shared/_feeditem.html.erb
<li id="<%= feeditem.id %>">
  <%= link_to gravatar_for(feeditem.user), feeditem.user %>
  <span class="user">
    <%= link_to feeditem.user.username, feeditem.user %>
  </span>
  <span class="content"><%= feeditem.content %></span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(feeditem.created_at) %> ago.
  </span>
</li>

app/views/shared/_user.html.erb
<li>
  <%= link_to gravatar_for(user) %>  
  <%= link_to user.username, user %>
  
</li>

app/views/shared/_userinfo.html.erb
<a href="<%= user_path(current_user) %>">
  <%= gravatar_for current_user %>
</a>
<h1>
  <%= current_user.username %>
</h1>
<span>
  <%= link_to "view my profile", current_user %>
</span>
<span>
 <%= pluralize(current_user.entries.count , "Post") %>
</span>

app/views/static_pages/account.html.erb
<% provide(:title, 'Account') %>
<h1>StaticPages#account</h1>
<p>Find me in app/views/static_pages/account.html.erb</p>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>
<h1>Help</h1>
<p>
  Get help on the Ruby on Rails Tutorial at the
  <a href="http://railstutorial.org/help">Rails Tutorial help page</a>.
  To get help on this sample app, see the
  <a href="http://railstutorial.org/book">Rails Tutorial book</a>.
</p>

app/views/static_pages/home.html.erb
<% provide(:title, 'Home') %>
<%if flash[:notice]%>
<%=flash[:notice]%>
<%end%>
<div class="center hero-unit">
    <h1>Have a nice day !!!</h1>

    <h2>
      This is the Ruby on rails' Test Following 
      <a href="http://railstutorial.org/">Ruby on Rails Tutorial by Michael Hartl</a>

    </h2>
    <% if !signed_in?%>
    <%= link_to "Sign up now!", signup_path, 
                                class: "btn btn-large btn-primary" %>
    <%end%>
  </div>

  <%= link_to image_tag("rails.png", alt: "Rails"), 'http://rubyonrails.org/' %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <%= render 'shared/error', object: f.object %>
  <div align="center">  
  <div class="field">
    <%= f.label :Username %>
	<%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :Password %>
	<%= f.password_field :password %> 
  </div>
  <div class="field">
    <%= f.label :Confirm_Password %>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="field">
    <%= f.label :fullname %>
    <%= f.text_field :fullname %>
  </div>
  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit "Confirm" , class: "btn btn-large btn-primary"%>
  </div>
</div>
<% end %>

app/views/users/edit.html.erb
<h1>Change profile</h1>
<%= render 'form' %>

app/views/users/index.html.erb
<% if @users.any? && signed_in? %>
  <ol class="entries">
    <%= render partial: '/shared/user', collection: @users%>
  </ol>  
<% end %>

app/views/users/new.html.erb
<h1>Sign Up</h2>

<%= render 'form' %>

app/views/users/show.html.erb
<% provide(:title, @user.username) %>
<div class="row">
  <aside>  
  <section>	
	  <%= gravatar_for @user %>
  </section> 

  </aside>
  <section>
    <p>Username: <%=@user.username%></p>
    <p>Fullname: <%=@user.fullname%></p>
    <p>Email: <%=@user.email%></p>	
  </section
</div>